name: Deregister Old AMIs

on:
  workflow_dispatch:
    inputs:
      REGION:
        description: 'AWS Region'
        required: true
        default: 'eu-west-1'
      WORK_REGION:
        description: 'AWS Work Region'
        required: true
        default: 'eu-central-1'
      KEEP_HISTORY:
        description: 'Number of recent AMIs to keep per app'
        required: false
        default: '3'
      LIMIT:
        description: 'Limit on number of app groups to process'
        required: false
        default: '0'
      TOOLKIT_VERSION:
        description: 'Version of the toolkit for script download'
        required: false
        default: 'default'
  schedule:
    - cron: '0 11,23 * * *'  # Runs daily at 11:00 AM and 11:00 PM

permissions:
  id-token: write
  contents: read

jobs:
  deregister_old_amis:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/ami-clean-old-origin.yml@default
    with:
      ROLE: "arn:aws:iam::339712742264:role/aws-mastermind-workflow-role"
      TOOLKIT_VERSION: ${{ inputs.TOOLKIT_VERSION || 'default' }}
      REGION: ${{ inputs.REGION || 'eu-west-1' }}
      WORK_REGION: ${{ inputs.WORK_REGION || 'eu-central-1' }}
      KEEP_HISTORY: ${{ inputs.KEEP_HISTORY || '3' }}
      LIMIT: ${{ inputs.limit || '0' }}