name: Deregister Old AMIs

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-central-1'
      keep_history:
        description: 'Number of recent AMIs to keep per app'
        required: false
        default: '3'
      limit:
        description: 'Limit on number of app groups to process'
        required: false
        default: '0'
      toolkit_version:
        description: 'Version of the toolkit for script download'
        required: false
        default: 'default'
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC; adjust as needed

env:
  DEFAULT_REGION: 'eu-central-1'
  DEFAULT_TOOLKIT_VERSION: 'default'
  DEFAULT_KEEP_HISTORY: 3
  DEFAULT_LIMIT: 0

jobs:
  deregister_old_amis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::339712742264:role/aws-mastermind-workflow-role"
          aws-region: "${{ inputs.region || env.DEFAULT_REGION }}"

      - name: Download deregister_old_ami_by_app.sh script
        run: |
          TOOLKIT_VERSION="${{ inputs.toolkit_version || env.DEFAULT_TOOLKIT_VERSION }}"
          echo "Downloading deregister_old_ami_by_app.sh script from toolkit version $TOOLKIT_VERSION..."
          wget https://raw.githubusercontent.com/inqwise/ansible-automation-toolkit/${TOOLKIT_VERSION}/ami/deregister_old_ami_by_app.sh -O deregister_old_ami_by_app.sh
          chmod +x deregister_old_ami_by_app.sh
          echo "deregister_old_ami_by_app.sh downloaded and made executable."

      - name: Run Deregister AMI Script
        run: |
          ./deregister_old_ami_by_app.sh \
            --region "${{ inputs.region || env.DEFAULT_REGION }}" \
            --keep-history "${{ inputs.keep_history || env.DEFAULT_KEEP_HISTORY }}" \
            --limit "${{ inputs.limit || env.DEFAULT_LIMIT }}"

      - name: Confirm Completion
        run: echo "Deregister Old AMIs workflow completed successfully."