name: AMI Copy Workflow

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:
    inputs:
      TOOLKIT_VERSION:
        description: 'Version of the Ansible Automation Toolkit'
        required: true
        default: 'default'
      REGION:
        description: 'AWS region for copy to (e.g., us-west-2)'
        required: true
        default: 'eu-west-1'
      SOURCE_REGION:
        description: 'AWS region from AMIs copied (e.g., eu-central-1)'
        required: true
        default: 'eu-central-1'
      SOURCE_ACCOUNT_ID:
        description: 'AWS account ID from AMIs copied (optional)'
        required: false
        default: ''
      PROFILE:
        description: 'AWS CLI profile to use (optional)'
        required: false
        default: ''

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  ami_copy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::339712742264:role/aws-mastermind-workflow-role"
          aws-region: "${{ inputs.REGION || 'eu-west-1' }}"  # Use default if not provided

      # Step 3: Download the copy_shared_amis.sh Script
      - name: Download copy_shared_amis.sh script
        run: |
          echo "Downloading copy_shared_amis.sh script from Ansible Automation Toolkit..."
          wget https://raw.githubusercontent.com/inqwise/ansible-automation-toolkit/${{ inputs.TOOLKIT_VERSION || 'default' }}/ami/copy_shared_amis.sh -O copy_shared_amis.sh
          chmod +x copy_shared_amis.sh
          echo "copy_shared_amis.sh downloaded and made executable."

      # Step 4: Execute the copy_shared_amis.sh Script
      - name: Copy Shared AMIs
        run: |
          echo "Starting AMI copying process..."

          # Initialize the command with mandatory arguments
          CMD="./copy_shared_amis.sh --source-region \"${{ inputs.SOURCE_REGION || 'eu-central-1' }}\" --region \"${{ inputs.REGION || 'eu-west-1' }}\" --toolkit-version \"${{ inputs.TOOLKIT_VERSION || 'default' }}\""

          # Add --source-account-id if SOURCE_ACCOUNT_ID input is provided
          if [[ -n "${{ inputs.SOURCE_ACCOUNT_ID || '' }}" ]]; then
            CMD+=" --source-account-id \"${{ inputs.SOURCE_ACCOUNT_ID || '' }}\""
          fi

          # Add --profile argument if PROFILE input is provided
          if [[ -n "${{ inputs.PROFILE || '' }}" ]]; then
            CMD+=" --profile \"${{ inputs.PROFILE || '' }}\""
          fi

          # Execute the command
          echo "Executing command: $CMD"
          eval "$CMD"

          echo "AMI copying process completed."