name: Cleanup Templates

on:
  workflow_dispatch:
    inputs:
      REGION:
        description: 'AWS Region'
        required: true
        default: 'eu-west-1'
      KEEP_HISTORY:
        description: 'Number of recent AMIs to keep per app'
        required: false
        default: '3'
      TOOLKIT_VERSION:
        description: 'Version of the toolkit for script download'
        required: false
        default: 'default'
      DRY_RUN:
        description: 'Enable dry-run mode'
        required: false
        default: true
        type: boolean
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC

permissions:
  id-token: write
  contents: read

jobs:
  deregister_old_amis:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/template-clean.yml@default
    with:
      ROLE: "arn:aws:iam::339712742264:role/aws-mastermind-workflow-role"
      TOOLKIT_VERSION: ${{ inputs.TOOLKIT_VERSION || 'default' }}
      REGION: ${{ inputs.REGION || 'eu-west-1' }}
      KEEP_HISTORY: ${{ inputs.KEEP_HISTORY || '3' }}
      DRY_RUN: ${{ inputs.DRY_RUN || true }}